/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author user
 */
public class KonversiSuhu extends javax.swing.JFrame {
    double celcius;
    double fahrenheit;
    double kelvin;
    double reamur;
    

    /**
     * Creates new form KonversiSuhu
     */
    public KonversiSuhu() {
        initComponents();
    }

    private void Celcius (){
      celcius = Double.parseDouble(txtSuhu.getText());
      fahrenheit=celcius * 1.8 + 32;
      kelvin =celcius +273.15;
      reamur = celcius*0.8;
      lblCelcius.setText(celcius+"celcius");
      lblfahrenheit.setText(fahrenheit+" Fahrenheit");
      lblkelvin.setText(kelvin+"Kelvin");
      lblReamur.setText(reamur+"Reamur");
    }
    
    private void Fahrenheit (){
    fahrenheit = Double.parseDouble(txtSuhu.getText());
    celcius=(fahrenheit -32)/1.8;
    reamur = (fahrenheit -32)/2.25;
    kelvin = (fahrenheit+459.67)/1.8;
    lblCelcius.setText(celcius+"celcius");
    lblfahrenheit.setText( fahrenheit +"fahrenheit");
    lblkelvin.setText(kelvin+"kelvin");
    lblReamur.setText(reamur+"reamur");
    }
    
    private void Kelvin (){
        kelvin = Double.parseDouble(txtSuhu.getText());
        fahrenheit = kelvin * 1.8 - 459.67;
        celcius = kelvin -273.15;
        reamur = (kelvin - 273.15)*0.8;
         lblCelcius.setText(celcius+"celcius");
         lblfahrenheit.setText( fahrenheit +"fahrenheit");
         lblkelvin.setText(kelvin+"kelvin");
         lblReamur.setText(reamur+"reamur");     
    }
    
    private void Reamur(){
        reamur = Double.parseDouble(txtSuhu.getText());
        fahrenheit =(reamur *2.25)+32;
        kelvin = (reamur/0.8)+273.15;
        celcius=reamur/0.8;
       lblCelcius.setText(celcius+"celcius");
         lblfahrenheit.setText( fahrenheit +"fahrenheit");
         lblkelvin.setText(kelvin+"kelvin");
         lblReamur.setText(reamur+"reamur");  
    }/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSuhu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnKonversi = new javax.swing.JButton();
        rbcelcius = new javax.swing.JRadioButton();
        rbfahrenheit = new javax.swing.JRadioButton();
        rbKelvin = new javax.swing.JRadioButton();
        rbreamur = new javax.swing.JRadioButton();
        btnReset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblCelcius = new javax.swing.JLabel();
        lblfahrenheit = new javax.swing.JLabel();
        lblkelvin = new javax.swing.JLabel();
        lblReamur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setText("Masukan suhu");

        btnKonversi.setText("Konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });

        rbcelcius.setText("Celcius");

        rbfahrenheit.setText("Fahrenheit");

        rbKelvin.setText("Kelvin");

        rbreamur.setText("reamur");

        btnReset.setText("reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel2.setText("HASIL KONVERSI :");

        lblCelcius.setText("CELCIUS");

        lblfahrenheit.setText("FAHRENHEIT");

        lblkelvin.setText("KELVIN");

        lblReamur.setText("REAMUR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbcelcius)
                        .addGap(9, 9, 9)
                        .addComponent(rbfahrenheit)
                        .addGap(10, 10, 10)
                        .addComponent(rbKelvin)
                        .addGap(10, 10, 10)
                        .addComponent(rbreamur))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnKonversi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset))
                    .addComponent(jLabel2)
                    .addComponent(lblCelcius)
                    .addComponent(lblfahrenheit)
                    .addComponent(lblkelvin)
                    .addComponent(lblReamur))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbcelcius)
                    .addComponent(rbfahrenheit)
                    .addComponent(rbKelvin)
                    .addComponent(rbreamur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKonversi)
                    .addComponent(btnReset))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCelcius)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblfahrenheit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblkelvin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblReamur)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        if(rbcelcius.isSelected()){
            Celcius();
        }else if(rbfahrenheit.isSelected()){
            Fahrenheit();
        }else if (rbKelvin.isSelected()){
            Kelvin();
        }else if (rbreamur.isSelected()){
            Reamur();
        }
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       txtSuhu.setText("");
       lblCelcius.setText("Celcius");
       lblfahrenheit.setText("Fahrenheit");
       lblkelvin.setText("Kelvin");
       lblReamur.setText("Reamur");
       rbcelcius.setSelected(false);
       rbfahrenheit.setSelected(false);
       rbKelvin.setSelected(false);
       rbreamur.setSelected(false);
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonversi;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCelcius;
    private javax.swing.JLabel lblReamur;
    private javax.swing.JLabel lblfahrenheit;
    private javax.swing.JLabel lblkelvin;
    private javax.swing.JRadioButton rbKelvin;
    private javax.swing.JRadioButton rbcelcius;
    private javax.swing.JRadioButton rbfahrenheit;
    private javax.swing.JRadioButton rbreamur;
    private javax.swing.JTextField txtSuhu;
    // End of variables declaration//GEN-END:variables
}
